apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: ingress-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /metrics
    prometheus.io/port:   '80'
spec:
  # backend:
  #  serviceName: grafana-ip-service
  #  servicePort: 3000
  rules:
    - host: grafana.gcp.cloudycelt.com
      http:
        paths: 
          - backend: 
              serviceName: grafana-ip-service
              servicePort: 3000

    - host: prometheus.gcp.cloudycelt.com
      http:
        paths: 
          - backend: 
              serviceName: prometheus-ip-service
              servicePort: 9090